apiVersion: extensions/v1beta1
kind: ReplicaSet 
metadata: 
  labels: 
    run: wordpess-deployment
    app: frontend
  name: mysql-rs
spec:  
  replicas: 1 
  selector:  
    matchLabels: 
      app: frontend
      run: wordpess-deployment
  template:  
    metadata: 
      labels:  
        app: frontend
        run: wordpess-deployment
    spec:  
      containers:  
      - image: mysql
        name: mysql-deployments
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mysql-credentials  
              key: credential 
        ports:  
        - containerPort: 3306
        volumeMounts:
        - name: mypv
          mountPath: /var/lib/mysql
      volumes:
      - name: mypv        
        persistentVolumeClaim:
          claimName: mypvc 
