apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: wordpess-deploy
    app: frontend
  name: wordpess-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: wordpess-deploy
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: wordpess-deploy
        app: frontend
    spec:
      containers:
      - image: wordpress
        name: wordpess-deploy
